{% set versions = {
    "4.6.10": "HEAD"
} %}

{% set version = environ.get('COMMIT_VERSION', None) %}
{% set version = version or versions.keys()|first %}
{% set version = version|string %}

package:
  name: {{ environ.get('ANACONDA_PACKAGE', "djangoh")|string|lower }}
  version: {{ environ.get('ANACONDA_VERSION', version)|replace("-", ".") }}

source:
  git_url: "https://gitlab.com/eic/mceg/DJANGOH-4.6.10"
  git_rev: {{ versions.get(version, "HEAD") }}
  patches:
    - "patches/0001-fix-default-makefile.patch"

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - {{ compiler('gfortran') }}

    - cmake
    - make

  host:
    - lhapdf5
    - lhapdf
    - cernlib

  run:
    - lhapdf5
    - lhapdf
    - cernlib


about:
  home: "https://gitlab.com/eic/mceg/DJANGOH-4.6.10"
  license: "MIT"
  summary: "DJANGOH simulates deep inelastic lepton-proton scattering for NC and CC events, including QED and QCD radiative effects"

extra:
  recipe-maintainers:
    - meiyasan
